---
- hosts: all
  connection: local
  vars:
    fisherman_plugins:
      - oh-my-fish/plugin-peco
      - oh-my-fish/plugin-aws
      - oh-my-fish/plugin-osx
      - jethrokuan/z
      - yoshiori/fish-peco_select_ghq_repository

  tasks:
    - include_tasks: tasks/main.yml
