---
# tasks file for ansible-role-set-fish
# setup fish
- name: install fish
  homebrew:
    name: fish
    state: present

- name: create fish directory
  file:
    path: "{{ ansible_env.HOME }}/.config/fish/functions"
    state: directory
    owner: y3-shimizu
    group: staff
    mode: 0750

- name: install fisherman
  get_url:
    url: https://git.io/fisher
    dest: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
    mode: 0644
    backup: yes


- name: Get list of a package
  shell: fish -lc "fisher ls | grep {{ item }}"
  register: installed_package_result
  with_items: "{{ fisherman_plugins }}"
  ignore_errors: yes
  changed_when: no

- name: install fisherman plugins
  shell: "fish -lc 'fisher add {{ item.item }}'"
  with_items: '{{ installed_package_result.results }}'
  when: item.failed
